channels:
  - 'https://t.me/rflive'
target_lang: 'EN'
logo:
  path: 'brand/logo.png'
  position: 'bottom-right'
  margin: 24
top_posts:
  enabled: true
  period_days: 7
  top_by:
    likes: 2
    comments: 2
    views: 2
